#!/bin/bash 
#set -x

if [ -d "venv" ]; then 
    rm -rf venv 
fi

python -m venv venv
source ./venv/bin/activate

echo "Installing all necessary packages ..."

pip install --upgrade pip
pip install libecl 
pip install webviz-config
pip install webviz-subsurface
pip install webviz-config-equinor
pip install black
pip install python-dotenv
pip install msal_extensions
pip install pygobject
pip install requests
pip install git+https://github.com/equinor/sumo-wrapper-python.git
pip install git+https://github.com/equinor/fmu-sumo.git

pip install .

echo "WebViz-4D installation completed"

