#!/bin/bash
#set -x

if [ -d "venv" ]; then
    rm -rf venv
fi

python -m venv venv
source ./venv/bin/activate

echo "Installing all necessary packages ..."

pip install --upgrade pip
pip install urllib3==1.26.15
pip install -r requirements.txt
pip install git+ssh://git@github.com/equinor/webviz-config
pip install webviz-config-equinor
pip install PyGObject==3.44.1
pip install black
pip install pylint
pip install pytest
pip install git+https://github.com/equinor/sumo-wrapper-python.git
pip install git+https://github.com/equinor/fmu-sumo.git

pip install -e .

echo "WebViz-4D installation completed"
