title: Webviz-4D RDDMS                            # Customize

shared_settings:
    field_name: JOHAN SVERDRUP 
    metadata_version: 0.4.2
    sumo:
        env_name: prod
        case_name: 24p12p4_histandpred_ff_20240922  
    rddms:
        dataspace: JS/Soumik_2
        difference_type: AttributeOfDifference
        coverage: Full
        
    label: RDDMS maps      # Customize             
                
    basic_well_layers:
        planned: Planned wells 
        drilled_wells: Drilled wells                        
        reservoir_sections: Reservoir sections   
          
    additional_well_layers:      
        production: Producers                                     
        injection: Injectors                                              
                
    well_folder: &wellfolder SMDA   
    top_reservoir: 
        name: Draupne Fm. 1 JS Top
        tag_name: depth_structural_model
        iter: pred
        real: realization-0 
        polygon_usage: 
            zones: True
            observed: True
            aggregated: True
    production_data: &production_data PDM          
    colormaps_folder: &colormaps_folder ../colormaps/     
    settings_file: &settings ../settings.yaml 
    interval_mode: &interval_mode normal
    default_interval: 2020-10-01-2019-10-01         
        
# ------------------------------
options:
  menu:
    show_logo: true
    bar_position: left
    drawer_position: left
    initially_pinned: true
    initially_collapsed: true

# ------------------------------
layout:
  - section: Webviz-4D TGX 
    content:
      # -----------------------------         
      - page: Front page 
        icon: home 
        content:  
          - Markdown: 
              markdown_file: ./front_page.md   
              
      # -------------------------------
      - group: Timelapse maps 
        icon: layers
        content:                    
          - page: Observed maps  
            content: 
              - SurfaceViewer4D: 
                  well_folder: *wellfolder               
                  production_data: *production_data      
                  colormaps_folder: *colormaps_folder       
                  settings_file:  *settings 
                  interval_mode: *interval_mode  
                  default_interval: 2022-05-15-2020-09-30                    
                  
                  map1_defaults:
                    data_source: rddms
                    difference_type: AttributeOfDifference
                    coverage: Full
                    attribute:  Max             # Customize
                    name: Total                     # Customize
                    map_type: observed                          # Customize 
                    seismic: Amplitude                          # Customize
                    difference: NotTimeshifted
                    interval: 2021-05-17-2020-09-30
                  map2_defaults:
                    data_source: rddms
                    difference_type: AttributeOfDifference
                    coverage: Full
                    attribute:  Max             # Customize
                    name: Total                     # Customize
                    map_type: simulated                          # Customize 
                    seismic: Amplitude                          # Customize
                    difference: NotTimeshifted
                    interval: 2021-05-17-2020-09-30
                  map3_defaults:
                    data_source: rddms
                    difference_type: AttributeOfDifference
                    coverage: Full
                    attribute:  Average             # Customize
                    name: Total                     # Customize
                    map_type: simulated                          # Customize 
                    seismic: SWAT                          # Customize
                    difference: NotTimeshifted
                    interval: 2021-05-17-2020-09-30
 
      
