# Configuration file: config.yaml    
title: WebViz-4D SUMO                                

shared_settings: 
    field_name: Johan Sverdrup  
    sumo:
        env_name: prod
        case_name: 25p0p3_histandpred_ff_16022025
        sumo_surfaces: True
    auto4d:
    osdu:
    fmu:
 
    label: Model 25.0.3 SUMO
    
    observed_maps: 
        realization_names: ["*"]                  
        iteration_names: [pred]                                   
        map_directories: [share/observations/maps/]   
        attributes: ["*"] 
        surface_names: ["*"]
        time_intervals: ["*"]
   
    basic_well_layers: 
        planned: Planned wells  
        drilled_wells: Drilled wells                         
        reservoir_sections: Reservoir sections              
        #active_production: Producers - active                      
        #active_injection: Injectors - active                        
        
    additional_well_layers:      
        production: Producers                                     
        injection: Injectors                                
         
    well_folder: SMDA  
    top_reservoir: 
        name: Draupne Fm. 1 JS Top 
        tag_name: depth_structural_model
        iter: pred
        real: realization-0 
        polygon_usage: 
            zones: True
            observed: True
            aggregated: True
    production_data: PDM 
    polygons_folder: SUMO
    colormaps_folder: &colormaps_folder ../colormaps/
    settings_file: &settings ../settings.yaml
    interval_mode: &interval_mode normal
                
# ------------------------------ 
options:
  menu:
    show_logo: true
    bar_position: left
    drawer_position: left
    initially_pinned: true
    initially_collapsed: true

# ------------------------------
layout:
  - section: Webviz-4D TGX 
    content:
      # -----------------------------         
      - page: Front page 
        icon: home
        content:                  
          - Markdown: 
              markdown_file: ./front_page.md  
              
      # -------------------------------
      - group: Timelapse maps   
        icon: layers
        content:                     
          - page: Observed maps 
            content:
              - SurfaceViewer4D: 
                  well_folder: SMDA
                  production_data: PDM
                  colormaps_folder: *colormaps_folder
                  settings_file: *settings 
                  interval_mode: *interval_mode 
                  default_interval: 2023-09-15-2020-10-01                    
                   
                  map1_defaults: 
                    data_source: sumo
                    difference_type: AttributeOfDifference
                    coverage: Full  
                    attribute:  max              # Customize 
                    name: total                     # Customize  
                    map_type: observed                          # Customize
                    seismic: amplitude                            # Customize 
                    difference:  NotTimeshifted                # Customize     
                    interval: 2021-05-15-2020-10-01    
                  map2_defaults: 
                    data_source: sumo
                    difference_type: AttributeOfDifference
                    coverage: Full 
                    attribute: max              # Customize
                    name: total                          # Customize
                    map_type: observed                          # Customize
                    seismic: amplitude                            # Customize 
                    difference: NotTimeshifted                  # Customize     
                    interval: 2022-05-15-2021-05-15 
                  map3_defaults: 
                    data_source: sumo
                    difference_type: AttributeOfDifference
                    coverage: Full 
                    attribute: max      # Customize
                    name: total                          # Customize 
                    map_type: observed                          # Customize
                    seismic:  amplitude                       # Customize 
                    difference: NotTimeshifted                  # Customize     
                    interval: 2023-05-15-2022-05-15                           
              
 
      
