fmu_directory: 

simulated_maps: 
    realization_names: [realization-*]
    ensemble_names: [iter-*]
    map_directories: [share/results/maps] 
    aggregated_directories: []
    
observed_maps: 
    realization_names: [realization-0]
    ensemble_names: [iter-0]
    map_directories: [share/observations/maps] 
    
    
depth_maps:
    top_reservoir: realization-0/iter-0/share/results/maps/topvolantis--ds_extract_geogrid.gri   
