title: Webviz-4D Johan Sverdrup                             # Customize

shared_settings:
    sumo_name: 23p20p0_histandpred_ff_20230917
    fmu_directory: 
    osdu_field: JOHAN SVERDRUP 
    auto4d_directory: 
  
    label: OSDU maps      # Customize             
                
    basic_well_layers:
        planned: Planned wells 
        drilled_wells: Drilled wells                        
        reservoir_section: Reservoir sections     
          
    additional_well_layers:      
        production: Producers                                    
        injection: Injectors                                              
                
    well_folder: &wellfolder SMDA 
    top_reservoir: 
        name: Draupne Fm. 1 JS Top
        tag_name: depth_structural_model
        iter: pred
        real: realization-0
        polygon_usage: 
            zones: True
            observed: True
            aggregated: True
    production_data: &production_data PDM   
    polygons_folder: &polygons_folder SUMO         
    colormaps_folder: &colormaps_folder ../colormaps/     
    settings_file: &settings ./settings.yaml    
    interval_mode: &interval_mode normal
    default_interval: 2020-10-01-2019-10-01         
        
# ------------------------------
options:
  menu:
    show_logo: true
    bar_position: left
    drawer_position: left
    initially_pinned: true
    initially_collapsed: true

# ------------------------------
layout:
  - section: Webviz-4D Windows/OSDU (2023)
    content:
      # -----------------------------         
      - page: Front page 
        icon: home
        content:  
          - Markdown: 
              markdown_file: ./front_page.md  
              
      # -------------------------------
      - group: Timelapse maps
        icon: layers
        content:                    
          - page: Observed maps  
            content: 
              - SurfaceViewer4D: 
                  well_folder: *wellfolder              
                  production_data: *production_data
                  polygons_folder: *polygons_folder       
                  colormaps_folder: *colormaps_folder      
                  selector_file: selectors.yaml
                  surface_metadata_file: surface_metadata.csv
                  attribute_maps_file: attribute_maps.csv
                  settings_file:  *settings 
                  interval_mode: *interval_mode                      
                  
                  map1_defaults:
                    attribute: Diff_maxn               # Customize   
                    name: TAasgard                      # Customize  
                    map_type: observed                         # Customize
                    ensemble: ---                            # Customize  
                    realization: ---                  # Customize     
                    interval: 2020-10-01-2019-10-01    
                  map2_defaults: 
                    attribute: dTS_maxp              # Customize
                    name: TAasgard                          # Customize
                    map_type: observed                          # Customize
                    ensemble: ---                            # Customize 
                    realization: ---                  # Customize     
                    interval: 2021-05-15-2020-10-01 
                  map3_defaults: 
                    attribute: TS_value      # Customize
                    name: IUTU_JS                          # Customize 
                    map_type: observed                          # Customize
                    ensemble: ---                            # Customize 
                    realization: ---                  # Customize     
                    interval: 2023-05-15-2019-10-01
                  default_interval: 2020-10-01-2019-10-01
 
      
