map_settings:
    colormaps_folder: ../colormaps/
    surface_metadata_file: ./surface_metadata.csv
    colormaps_settings: ./attribute_maps.csv
    default_colormap: magic 
    
    attribute_settings: 
        Diff_maxn:
            color:   geoprobe_r
            min:  -800
            max:   800  
        Diff_maxp:
            color:   geoprobe_r
            min:  -800
            max:   800  
        DiffTS_maxn:
            color:   geoprobe_r
            min:  -800
            max:   800  
        DiffTS_maxp:
            color:   geoprobe_r
            min:  -800
            max:   800  
        dTS_maxp:
            color:   geoprobe_r
            min:  -5
            max:   5  
        dTS_maxn:
            color:   geoprobe_r
            min:  -5
            max:   5 
        TS_value:
            color:   geoprobe_r
            min:  -2
            max:   2           
        amplitude_full_min:
            color:   geoprobe_r
            min:  -800
            max:   800   
        amplitude_full_max:
            color:   geoprobe_r
            min:  -800
            max:   800
        amplitude_full_mean:
            color:   geoprobe_r
            min:  -400
            max:   400
        amplitude_full_rms:
            color:   Purples
            min:   0
            max:   400
        amplitude_near_min:
            color:   geoprobe_r
            min:  -800
            max:   800   
        amplitude_near_max:
            color:   geoprobe_r
            min:  -800
            max:   800
        amplitude_near_mean:
            color:   geoprobe_r
            min:  -400
            max:   400
        amplitude_near_rms:
            color:   Purples
            min:   0
            max:   400  
        relai_full_max: 
            color:   geoprobe_r
            min:  -0.04
            max:   0.04 
        relai_full_min: 
            color:   geoprobe_r
            min:  -0.02
            max:   0.02 
        relai_full_rms: 
            color:   Purples
            min:   0
            max:   0.02    
        relai_full_mean: 
            color:   geoprobe_r
            min:  -0.03
            max:   0.03 
        relai_near_max: 
            color:   geoprobe_r
            min:  -0.02
            max:   0.02 
        relai_near_min: 
            color:   geoprobe_r
            min:  -0.02
            max:   0.02 
        relai_near_rms: 
            color:   Purples
            min:   0
            max:   0.02    
        relai_full_mean: 
            color:   geoprobe_r
            min:  -0.03
            max:   0.03             
        timeshift_mean:
            color:   geoprobe_r
            min:  -1
            max:   1         
        timestrain_mean:
            color:   geoprobe_r
            min:  -5
            max:   5  
        timestrain_min:
            color:   geoprobe_r
            min:  -5
            max:   5 
        timestrain_max:
            color:   geoprobe_r
            min:  -5
            max:   5              
        timestrain_rms:
            color:   Purples
            min:   0
            max:   3    
        average_swat:
            color:   geoprobe_r
            min: -0.5
            max: 0.5
        average_pressure:
            color:   geoprobe_r
            min: -15
            max:  15
        oilthickness:
            color:   geoprobe_r
            min: -4
            max:  4
        oilthickness_rf:
            color:   geoprobe_r
            min: -4
            max:  4
        mobile_oilthickness_rf:
            color:   geoprobe_r
            min: -4
            max:  4
            
well_colors:
    default: black
    oil_open: lime
    oil_production: green
    production: green
    gas_open: salmon
    gas_production: red
    gas_injection:  red
    water_injection: cyan
    injection: cyan
    wag_injection: cyan   
    planned: purple   
    
polygon_colors:
    owc_outline: lightslategray
    goc_outline: red
    field_outline: lightslategray
    faults: gray  
        
date_labels:
    20191001: PRM19aut
    20201001: PRM20aut
    20210515: PRM21spr
    20220515: PRM22spr
    20230515: PRM23spr
    
prod_data_intervals: 


    
 
